### GET PACIENTES
GET http://localhost:3000/api/patients

### POST PACIENTES
POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "JuanPACIENTE",
  "surname": "PerezPACIENTE",
  "birthdate": "1990-01-01",
  "nationality": "Argentina",
  "typeOfIdentification": "DNI",
  "identification": "1234567890",
  "sex": "Masculino",
  "email": "juan.perez@example.com",
  "phone": "1234567890",
  "age": 30,
  "ageRange": "Adulto"
}


### GET PACIENTE POR ID
GET http://localhost:3000/api/patients/2


### PUT PACIENTE POR ID
PUT http://localhost:3000/api/patients/2
Content-Type: application/json

{
  "name": "EDITED NAME",
  "surname": "EDITED SURNAME",
  "email": "edited.email@example.com"
}


### DELETE PACIENTE POR ID
DELETE http://localhost:3000/api/patients/4


### GET NOTAS DE PACIENTE
GET http://localhost:3000/api/patients/6876b0e160eec5d39c52d4dd/notes


### POST NOTA DE PACIENTE
POST http://localhost:3000/api/patients/6876b0e160eec5d39c52d4dd/notes
Content-Type: application/json

{
  "title": "Nota de prueba",
  "content": "Esta es una nota de prueba"
}


### GET NOTA POR ID
GET http://localhost:3000/api/patients/6876a76eeb5a5fd67ea6cbdb/notes/6876b4141085482aacbac05b


### PUT NOTA POR ID
PUT http://localhost:3000/api/patients/6876a76eeb5a5fd67ea6cbdb/notes/6876b5091aae61a14aef0802 
Content-Type: application/json

{
  "title": "NOTA EDITADA",
  "content": "ESTA ES UNA NOTA EDITADA"
}


### DELETE NOTA POR ID
DELETE http://localhost:3000/api/patients/6876a76eeb5a5fd67ea6cbdb/notes/6876b5091aae61a14aef0802


### GET MATERIALES DE PACIENTE
GET http://localhost:3000/api/patients/6876b0e160eec5d39c52d4dd/materials


### POST MATERIAL DE PACIENTE
POST http://localhost:3000/api/patients/6876b0e160eec5d39c52d4dd/materials
Content-Type: application/json

{
  "title": "Material de prueba",
  "content": "Este es un material de prueba"
}


### GET MATERIAL POR ID
GET http://localhost:3000/api/patients/6876b0e160eec5d39c52d4dd/materials/6876b76e0a33340f7c94c47b


### PUT MATERIAL POR ID
PUT http://localhost:3000/api/patients/6876b0e160eec5d39c52d4dd/materials/6876b76e0a33340f7c94c47b
Content-Type: application/json

{
  "title": "MATERIAL EDITADO",
  "content": "ESTE ES UN MATERIAL EDITADO"
}


### DELETE MATERIAL POR ID
DELETE http://localhost:3000/api/patients/6876b0e160eec5d39c52d4dd/materials/6876b76e0a33340f7c94c47b



### GET USUARIO PSICÓLOGO
GET http://localhost:3000/api/users


### POST USUARIO PSICÓLOGO
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "PabloUSUARIO",
  "surname": "GarciaUSUARIO",
  "email": "pablo.garcia@example.com",
  "passwordHash": "123456"
}